dist: trusty
language: node_js

node_js:
  - 10

services:
  - docker

script:
  - npm run build
  - npm test
  - ./bin/speedo run http://www.saucedemo.com -n "Speedo CI Build"
  - ./bin/speedo analyze "Speedo CI Build"

after_script:
  - ./node_modules/.bin/codecov

deploy:
  provider: script
  script: "npm install && npm run docker"
  on:
    tags: true
