dist: trusty
language: node_js

node_js:
  - 10

services:
  - docker

script:
  - npm run build
  - npm test
  - ./bin/speedo run http://www.saucedemo.com
  - ./bin/speedo analyze "Performance test for http://www.saucedemo.com (on "Good 3G" and 4x CPU throttling)"

after_script:
  - ./node_modules/.bin/codecov

deploy:
  provider: script
  script: "npm install && npm run docker"
  on:
    tags: true
